import 'package:dpl_ecommerce/models/voucher.dart';

class VoucherRepo {
  final List<Voucher> list = [
    Voucher(
      discountPercent: 15,
      expDate: DateTime.now().add(const Duration(days: 3)),
      id: "voucher01",
      productID: "product01",
      shopID: "shopID01",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 20,
      expDate: DateTime.now().add(const Duration(days: 5)),
      id: "voucher02",
      productID: "product02",
      shopID: "shopID02",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 18,
      expDate: DateTime.now().add(const Duration(days: 4)),
      id: "voucher03",
      productID: "product03",
      shopID: "shopID03",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 15,
      expDate: DateTime.now().add(const Duration(days: 3)),
      id: "voucher04",
      productID: "product04",
      shopID: "shopID04",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 22,
      expDate: DateTime.now().add(const Duration(days: 6)),
      id: "voucher05",
      productID: "product05",
      shopID: "shopID05",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 15,
      expDate: DateTime.now().add(const Duration(days: 3)),
      id: "voucher06",
      productID: "product06",
      shopID: "shopID06",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 25,
      expDate: DateTime.now().add(const Duration(days: 7)),
      id: "voucher07",
      productID: "product07",
      shopID: "shopID07",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 15,
      expDate: DateTime.now().add(const Duration(days: 3)),
      id: "voucher08",
      productID: "product08",
      shopID: "shopID08",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 30,
      expDate: DateTime.now().add(const Duration(days: 8)),
      id: "voucher09",
      productID: "product09",
      shopID: "shopID09",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 15,
      expDate: DateTime.now().add(const Duration(days: 3)),
      id: "voucher10",
      productID: "product10",
      shopID: "shopID10",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 35,
      expDate: DateTime.now().add(const Duration(days: 9)),
      id: "voucher11",
      productID: "product11",
      shopID: "shopID11",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 15,
      expDate: DateTime.now().add(const Duration(days: 3)),
      id: "voucher12",
      productID: "product12",
      shopID: "shopID12",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 40,
      expDate: DateTime.now().add(const Duration(days: 10)),
      id: "voucher13",
      productID: "product13",
      shopID: "shopID13",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 15,
      expDate: DateTime.now().add(const Duration(days: 3)),
      id: "voucher14",
      productID: "product14",
      shopID: "shopID14",
      releasedDate: DateTime.now(),
    ),
    Voucher(
      discountPercent: 45,
      expDate: DateTime.now().add(const Duration(days: 11)),
      id: "voucher15",
      productID: "product15",
      shopID: "shopID15",
      releasedDate: DateTime.now(),
    ),
  ];
}
