import 'dart:ui';
import 'package:dpl_ecommerce/utils/constants/size_utils.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class AppTheme {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: colorScheme.onPrimaryContainer.withOpacity(1),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.deepOrange800,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(2.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.primaryContainer,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(4.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.gray200,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.blueGray300,
          fontSize: 16.sp,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 14.sp,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 12.sp,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: appTheme.black900,
          fontSize: 24.sp,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        labelLarge: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 12.sp,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        labelMedium: TextStyle(
          color: appTheme.blueGray300,
          fontSize: 10.sp,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        labelSmall: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: 8.sp,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 20.sp,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        titleMedium: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: 16.sp,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 14.sp,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFFF9FAFB),
    primaryContainer: Color(0XFF1D4ED8),

    // Error colors
    errorContainer: Color(0XFF10B981),
    onError: Color(0XFFFFE0B7),
    onErrorContainer: Color(0XFF3E1304),

    // On colors(text colors)
    onPrimary: Color(0XFF1F2937),
    onPrimaryContainer: Color(0XA3FFFFFF),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber700 => Color(0XFFF59E0B);

  // Black
  Color get black900 => Color(0XFF000000);

  // BlueGray
  Color get blueGray100 => Color(0XFFD1D5DB);
  Color get blueGray300 => Color(0XFF9CA3AF);

  // BlueGrayf
  Color get blueGray7000f => Color(0X0F4B5563);

  // DeepOrange
  Color get deepOrange800 => Color(0XFFCC6522);

  // Gray
  Color get gray100 => Color(0XFFF3F4F6);
  Color get gray10001 => Color(0XFFEFF6FF);
  Color get gray10002 => Color(0XFFECFDF5);
  Color get gray200 => Color(0XFFE5E7EB);
  Color get gray20001 => Color(0XFFEBEDEE);
  Color get gray50 => Color(0XFFFDFBFB);
  Color get gray600 => Color(0XFF6B7280);

  // LightBlue
  Color get lightBlue50 => Color(0XFFECFEFF);

  // Orange
  Color get orange900 => Color(0XFFEA580C);

  // Red
  Color get red500 => Color(0XFFEF4444);

  // Yellow
  Color get yellow50 => Color(0XFFFFF7ED);
  Color get gray300 => Color(0XFFDADADA);
}

PrimaryColors get appTheme => AppTheme().themeColor();
ThemeData get theme => AppTheme().themeData();

class MyTheme {
  static Color xColor = Color.fromRGBO(7, 63, 123, 1);
  static const Color app_accent_color = Color.fromRGBO(7, 63, 123, 1);
  static Color app_accent_color_extra_light =
      Color.fromRGBO(233, 233, 240, 1.0);

  static Color accent_color = Color.fromRGBO(18, 94, 175, 1);
  static Color accent_color_2 = Color.fromRGBO(47, 119, 196, 1);
  static Color splash_screen_color = Colors.white;
  static Color login_reg_screen_color =
      Color(0xFFFFFFFF); // if not sure , use the same color as accent color
  static Color button_color = Color(0xFF212464);

  static const Color app_accent_border = Color.fromRGBO(224, 224, 224, 1);
  static const Color app_accent_shado = Color.fromRGBO(0, 0, 0, 0.16);
  static const Color app_accent_tranparent = Color.fromRGBO(0, 0, 0, 0.5);
  static Color white = Color.fromRGBO(255, 255, 255, 1);
  static const Color noColor = Color.fromRGBO(255, 255, 255, 0);
  static Color light_grey = Color.fromRGBO(239, 239, 239, 1);
  static Color dark_grey = Color.fromRGBO(112, 112, 112, 1);
  static Color medium_grey = Color.fromRGBO(132, 132, 132, 1);
  static Color medium_grey_50 = Color.fromRGBO(132, 132, 132, .5);
  static Color grey_153 = Color.fromRGBO(153, 153, 153, 1);
  static const Color font_grey = Color.fromRGBO(73, 73, 73, 1);
  static Color textfield_grey = Color(0xFFEDEDED);
  static Color golden = Color.fromRGBO(248, 181, 91, 1);
  static Color red = Color.fromRGBO(255, 0, 0, 1.0);
  static Color green = Color.fromRGBO(52, 168, 83, 1.0);
  static Color shimmer_base = Colors.grey.shade50;
  static Color shimmer_highlighted = Colors.grey.shade200;
  static const black = Color.fromRGBO(0, 0, 0, 1);

  static Color borderColor = Color.fromARGB(226, 63, 63, 61);
  static Color background = Color(0xccefeeee);
  static Color accent_color_shadow = Color.fromRGBO(229, 65, 28, .40);
  static Color soft_accent_color = Color.fromRGBO(254, 234, 209, 1);

  static Color blue_grey = Color.fromRGBO(168, 175, 179, 1);
  static Color dark_font_grey = Color.fromRGBO(62, 68, 71, 1);
  static Color amber = Color.fromRGBO(254, 234, 209, 1);
  static Color amber_medium = Color.fromRGBO(254, 240, 215, 1);
  static Color golden_shadow = Color.fromRGBO(255, 168, 0, .4);
  static Color? green_light = Colors.green[200];

  static Color btn_checkout = Colors.blue;
  static Color get orange900 => Color(0XFFEA580C);
}
