// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvYPQtWkglo82ULGV_fQ0qF6qwQtI5w5o',
    appId: '1:573290240283:web:19665cceff745bb604dbbe',
    messagingSenderId: '573290240283',
    projectId: 'dpl-ecommerce',
    authDomain: 'dpl-ecommerce.firebaseapp.com',
    storageBucket: 'dpl-ecommerce.appspot.com',
    measurementId: 'G-2YJKG18CK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJb7yN-cd_LYzZP30Z4ImOJbuGBSPpX6w',
    appId: '1:573290240283:android:35b416af7738c59904dbbe',
    messagingSenderId: '573290240283',
    projectId: 'dpl-ecommerce',
    storageBucket: 'dpl-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxyfdU0VNT0nyvddtWVa9K-tVNgYpsZS8',
    appId: '1:573290240283:ios:12053ba2392e1bf104dbbe',
    messagingSenderId: '573290240283',
    projectId: 'dpl-ecommerce',
    storageBucket: 'dpl-ecommerce.appspot.com',
    iosBundleId: 'com.example.dplEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxyfdU0VNT0nyvddtWVa9K-tVNgYpsZS8',
    appId: '1:573290240283:ios:f64634117d9535e104dbbe',
    messagingSenderId: '573290240283',
    projectId: 'dpl-ecommerce',
    storageBucket: 'dpl-ecommerce.appspot.com',
    iosBundleId: 'com.example.dplEcommerce.RunnerTests',
  );
}
